name: fx_trader_app
description: FX Trading Mobile Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  go_router: ^14.2.0
  dio: ^5.4.4
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  equatable: ^2.0.5
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
